name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - mlflow
  - ipython
  - ipykernel
  - notebook
  - jupyter notebook
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip

  - pip:
      - wandb
